# Generated by Django 4.1 on 2024-11-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitem_latitude_todoitem_longitude_todoitem_radius'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={},
        ),
        # migrations.RemoveField(
        #     model_name='todoitem',
        #     name='completed',
        # ),
        # migrations.RemoveField(
        #     model_name='todoitem',
        #     name='radius',
        # ),
        # migrations.RemoveField(
        #     model_name='todoitem',
        #     name='updated_at',
        # ),
        migrations.AddField(
            model_name='todoitem',
            name='category',
            field=models.CharField(choices=[('work', '仕事'), ('personal', '個人'), ('other', 'その他')], default='General', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='latitude',
            field=models.FloatField(default='35'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='longitude',
            field=models.FloatField(default='139'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
