# Generated by Django 4.1 on 2024-12-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_todoitem_completed_remove_todoitem_radius_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='radius',
            field=models.FloatField(default=100.0),
        ),
    ]
